### ISSUE TITLE
Would you contribute your changes to sweetyrdf/easyrdf?

### ISSUE THREAD

**Issue by k00ni** [acdh-oeaw/easyrdf#2]
Hello,

i've created a fork of njh/easyrdf, which aims to be a successor of EasyRdf.

Link: https://github.com/sweetyrdf/easyrdf

@zozlak made further changes to EasyRdf which seem helpful, for what i've checked so far: https://github.com/sweetyrdf/easyrdf/compare/master...acdh-oeaw:master#files_bucket

I already started to merge in pull requests from njh/easyrdf, which add a few fixes and features. It would be great to have your changes on board also. Are you willing to help me merge in some of your code?

Thank you in advance.

**Comment by zozlak** [comment]
Dear Konrad, I am happy to help but some stuff might be difficult.

The biggest problem is for sure the way original EasyRdf supports SPARQL path-like expressions. The original parsing is broken by design and makes it impossible to use fully-qualified URIs (slash in the URI is treated as the path separator, sic!). In my fork it was completely turned off. I don't use these path-like expressions anyway but I definitely need support for fully-qualified URIs. I'm afraid providing a solution which will be both backward-compatible and properly support fully-qualified URIs might be difficult and may introduce a performance penalty (cause more complex parsing algorithm will be required).

There are some fixes which were pretty ad-hoc ones and while they provide a significant benefits (e.g. few orders of magnitude faster ttl parsing) I consider their implementation quick&dirty and they should be probably provided in a better way (e.g. by introducing some input buffering abstraction layer within the library).

**Comment by k00ni** [comment]
Hello Mateusz,

can you give me a hint, which classes and functions are related to the SPARQL path-like expressions?

You wrote:
> There are some fixes which were pretty ad-hoc ones and while they provide a significant benefits (e.g. few orders of magnitude faster ttl parsing) I consider their implementation quick&dirty and they should be probably provided in a better way (e.g. by introducing some input buffering abstraction layer within the library).

If they fix things or improve performance, than i would like those changes in the code. I suggest you create a pull request for each group of changes and we see, how far we get. What do you think?

**Comment by zozlak** [comment]
SPARQL path-like expressions are implemented in https://github.com/sweetyrdf/easyrdf/blob/master/lib/Graph.php#L605-L624 . The problem is caused by `explode('/', $propertyPath)`. In my fork the workaround for it is to assure all methods calling `EasyRdf\Graph::get()` pass an `EadyRdf\Resource` object as the second argument - see https://github.com/njh/easyrdf/compare/0.10.0-alpha.1...acdh-oeaw:0.11.0 

> I suggest you create a pull request for each group of changes and we see, how far we get. What do you think?

I think it will take ages this way. I'm developing this library only when I'm forced to do so. I can find time to help someone understand and merge my changes if (s)he finds them useful but I can't really see myself proactively backporting my code.

**Comment by k00ni** [comment]
Your "SPARQL path-like expression" fork seems to be compatible with the current version and allows both ways, right? Or does it break backward compatibility of njh/easyrdf 0.10.x?

> I think it will take ages this way. [...]

OK, no problem. Maybe in the future one can grab further code from your fork. Based on your statement i assume a fork is definitely not possible.

**Comment by zozlak** [comment]
> Your "SPARQL path-like expression" fork seems to be compatible with the current version

Yes and no. It doesn't change the `EasyRdf\Graph::get()` behaviour but it enforces all `EasyRdf\Resource` methods taking the `$property` parameter to threat it like a single property (and not as a SPARQL path-like expression).

It's hard to say if the limitation I'm introducing is a bug or a feature. In the `EasyRdf\Resource` methods' documentation the `$property` parameter is described as *The property name* while in the `EasyRdf\Graph::get()` documentation the `$property` parameter is described as *A valid property path*. So maybe my adjustment only enforces what previous developers assumed (that for `Graph` it can be a SPARQL path-like expression and for `Resouce` just a single property name). Or maybe previous developers forgot to update the documentation while introducing support for the SPARQL path-like expressions (which is in my opinion broken by design cause it can't suppor fully qualified URIs). I really can't tell but I also don't want to spend time on figuring it out.

**Comment by zozlak** [comment]
I updated my fork so it:

* Uses your CI config.
* Passes all the tests.

In the next week I will try to find time to prepare a pull request with ntriples and turtle serializer/parser  enhancements (much faster big turtle parsing, much faster serialization of ntriples containing non-lower-ascii characters, more [standards conformant](https://www.w3.org/TR/turtle/#sec-grammar) serialization of ntriples and turtle, more standards conformant ntriples parsing).

Then we can think about the Resource class which (for reasons I already menioned) is tricky and may require some discussion.

**Comment by k00ni** [comment]
> In the next week I will try to find time to prepare a pull request with ntriples and turtle serializer/parser enhancements

Your changes seem promising and i look forward to it. I try to help when i can and thank you for your efforts here.

**Comment by k00ni** [comment]
Just wanted to say thank you again for your contributions. This issue can be closed now.
